server:
  port: 9999
  servlet:
    context-path: /
  # 优化Tomcat性能
  tomcat:
    threads:
      max: 200
    max-connections: 8192
    accept-count: 100
    connection-timeout: 5000
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: ideafly-api-service
  profiles:
    active: prod
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://18.183.232.3:8545/ideafly?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用HikariCP连接池并优化
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  redis:
    host: 18.183.232.3
    port: 8546
    password: 123456
    database: 0
    # 优化Redis连接
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: 100ms
logging:
  level:
    com.ideafly.mapper: warn
    com.baomidou: warn
    org.springframework: warn
  file:
    path: ./logs
knife4j:
  enable: true
  setting:
    enable-footer: true
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.ideafly
# application.yml

aliyun:
  sms:
    accessKeyId: LTAI5tPrMEnscMzcURdjnT3b  # 替换为你的 AccessKeyId
    accessKeySecret: MkJpV4enT9YMM7IWNB24MoCfaUxiWX # 替换为你的 AccessKeySecret
    signName: 智飞  # 替换为你的短信签名
    templateCode: SMS_478500181  # 替换为你的短信模板 Code
jwt:
  secret: VyacG/skIsQm9uJLXc14MlI0fM9dzoMX/133l/6jrS8=  # 替换成你的 JWT 密钥 (务必保密!)
  expiration: 60000 # Access Token过期时间，1分钟(单位毫秒)
  refreshExpiration: 180000 # Refresh Token过期时间，5分钟(单位毫秒)

# Telegram 配置
telegram:
  bot:
    token: 7465936604:AAEb5kzWAxJoBd5coMWh50toyCvBjUUIt5k # Telegram Bot Token
    username: 7465936604 # Telegram Bot Username (Numeric ID)

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 关闭控制台日志输出
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 开启二级缓存
    cache-enabled: true
    # 设置本地缓存范围
    local-cache-scope: statement
    # 关闭JDBC操作资源自动释放
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
  # 全局配置
  global-config:
    db-config:
      # 使用自增策略
      id-type: auto
    # 禁用banner
    banner: false