server:
  port: 9999
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: ideafly-api-service
  profiles:
    active: prod
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://18.183.232.3:8546/ideafly?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
logging:
  level:
    com.ideafly.mapper: debug
    com.baomidou: debug
    org.springframework: INFO
  file:
    path: ./logs
knife4j:
  enable: true
  setting:
    enable-footer: true
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.ideafly
# application.yml

aliyun:
  sms:
    accessKeyId: LTAI5tPrMEnscMzcURdjnT3b  # 替换为你的 AccessKeyId
    accessKeySecret: MkJpV4enT9YMM7IWNB24MoCfaUxiWX # 替换为你的 AccessKeySecret
    signName: 智飞  # 替换为你的短信签名
    templateCode: SMS_478500181  # 替换为你的短信模板 Code
jwt:
  secret: VyacG/skIsQm9uJLXc14MlI0fM9dzoMX/133l/6jrS8=  # 替换成你的 JWT 密钥 (务必保密!)
  expiration: 604800000  # Token过期时间，7天(单位毫秒) - 从1小时(3600000)改为7天
  refreshExpiration: 2592000000 # Refresh Token过期时间，30天(单位毫秒) - 从1天(86400000)改为30天

# Telegram 配置
telegram:
  bot:
    token: 7465936604:AAEb5kzWAxJoBd5coMWh50toyCvBjUUIt5k # Telegram Bot Token
    username: 7465936604 # Telegram Bot Username (Numeric ID)

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml