server:
  port: 9999
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ideafly-api-service
  profiles:
    active: prod
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://113.44.79.120:3306/ideafly?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
logging:
  level:
    com.ideafly.mapper: debug
    com.baomidou: debug
    org.springframework: INFO
  file:
    path: ./logs
knife4j:
  enable: true
  setting:
    enable-footer: true
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.ideafly
# application.yml

aliyun:
  sms:
    accessKeyId: LTAI5tPrMEnscMzcURdjnT3b  # 替换为你的 AccessKeyId
    accessKeySecret: MkJpV4enT9YMM7IWNB24MoCfaUxiWX # 替换为你的 AccessKeySecret
    signName: 智飞  # 替换为你的短信签名
    templateCode: SMS_478500181  # 替换为你的短信模板 Code
jwt:
  secret: VyacG/skIsQm9uJLXc14MlI0fM9dzoMX/133l/6jrS8=  # 替换成你的 JWT 密钥 (务必保密!)
  expiration: 3600000  # Token 过期时间，例如 1小时 (单位毫秒)
  refreshExpiration: 86400000 # Refresh Token 过期时间，例如 1天 (单位毫秒)